name: Update Profile Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"  # midnight + noon UTC

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Profile Image
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Update profile image \n\nCo-Authored-By: Mithun Gowda B <mithungowda.b7411@gmail.com>"
          git push -f
